-- M0: base database + warehouse cost hygiene
-- Run as ACCOUNTADMIN (resource monitor creation specifically requires it)

CREATE DATABASE IF NOT EXISTS AIRBNB;

ALTER WAREHOUSE COMPUTE_WH SET AUTO_SUSPEND = 60;

CREATE RESOURCE MONITOR IF NOT EXISTS AIRBNB_PROJECT_CAP WITH CREDIT_QUOTA = 10
  TRIGGERS ON 50 PERCENT DO NOTIFY
           ON 90 PERCENT DO SUSPEND;

ALTER WAREHOUSE COMPUTE_WH SET RESOURCE_MONITOR = AIRBNB_PROJECT_CAP;
