-- M3 Lesson 3: scoped role for day-to-day dbt work, replacing ACCOUNTADMIN
-- Run as a role with MANAGE GRANTS / role-creation rights (ACCOUNTADMIN or SECURITYADMIN)

CREATE ROLE IF NOT EXISTS TRANSFORMER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE AIRBNB TO ROLE TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE AIRBNB TO ROLE TRANSFORMER;

-- PUBLIC schema pre-dates TRANSFORMER (created earlier under ACCOUNTADMIN),
-- so it needs explicit grants. Anything TRANSFORMER creates itself, it owns
-- automatically -- see 02_schemas.sql.
GRANT USAGE ON SCHEMA AIRBNB.PUBLIC TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA AIRBNB.PUBLIC TO ROLE TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA AIRBNB.PUBLIC TO ROLE TRANSFORMER;

GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO USER MOUDA;

-- After running this: update ~/.dbt/profiles.yml role: ACCOUNTADMIN -> TRANSFORMER
-- and confirm with `dbt debug`.
