

CREATE ROLE IF NOT EXISTS TRANSFORMER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE AIRBNB TO ROLE TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE AIRBNB TO ROLE TRANSFORMER;


GRANT USAGE ON SCHEMA AIRBNB.PUBLIC TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA AIRBNB.PUBLIC TO ROLE TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA AIRBNB.PUBLIC TO ROLE TRANSFORMER;

GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO USER MOUDA;

