

USE ROLE TRANSFORMER;

CREATE STAGE IF NOT EXISTS AIRBNB.RAW.CSV_STAGE;


GRANT READ ON STAGE AIRBNB.RAW.CSV_STAGE TO ROLE TRANSFORMER;
GRANT WRITE ON STAGE AIRBNB.RAW.CSV_STAGE TO ROLE TRANSFORMER;
