-- M3 Lesson 6: load the staged CSVs into the RAW tables
-- Run as TRANSFORMER

USE ROLE TRANSFORMER;

COPY INTO AIRBNB.RAW.LISTINGS
FROM @AIRBNB.RAW.CSV_STAGE/listings.csv
FILE_FORMAT = AIRBNB.RAW.CSV_FORMAT;

COPY INTO AIRBNB.RAW.HOSTS
FROM @AIRBNB.RAW.CSV_STAGE/hosts.csv
FILE_FORMAT = AIRBNB.RAW.CSV_FORMAT;

COPY INTO AIRBNB.RAW.BOOKINGS
FROM @AIRBNB.RAW.CSV_STAGE/bookings.csv
FILE_FORMAT = AIRBNB.RAW.CSV_FORMAT;
